### ISSUE TITLE
How to use this and create plot?

### ISSUE THREAD

**Issue by sariya** [diazale/gt-dimred#1]
Dear alex,
Thanks for this repository. I am interested to construct UMAP plot for genetics ancestry in an admixed population 

https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008432

I performed UMAP as: 

`python gt-dimred/scripts/general_umap_script.py -dset  input_pc_umap.txt -pc 15 -nn 10 -md 0.001 -outdir umap_out  -head T -log log_dir
`
The output has two columns, number of rows is equal to the number of individuals in the initial PCs data.

What does the output represent and how do I create (UMAP/t-sne?) graphics as similar to the published manuscript using python or R?

**Comment by diazale** [comment]
The output represents the 2D coordinates as generated by UMAP. It is one possible way of presenting how similar individuals are to each other. From there you can plot it in R or Python using your preferred packages and colour the points by whatever variables are available. I used matplotlib for the manuscript but you can use whatever you're most comfortable with (you can easily do the same in ggplot2 in R).

Here are some examples of my code that does this:
https://github.com/diazale/gt-dimred/blob/master/HRS_plotting.Rmd
https://github.com/diazale/gt-dimred/blob/master/UKBB_cleaned.ipynb
