### ISSUE TITLE
umap for UKB first 10 PC, I got a different plot

### ISSUE THREAD

**Issue by jielab** [diazale/gt-dimred#3]
Hi, there:

Below is the UMAP based on 10 PC of UKB data, copied from your paper:

![image](https://github.com/diazale/gt-dimred/assets/26947455/0e1a2a49-0285-4bc4-9530-e987cd214cb3)

I used your script **general_umap_script.py -head T -dset ukb.pc.txt -pc 10 -nn 10 -md 0.001 -nc 2 -outdir umap -log umap** and got the following plot (let's ignore the group color for now).

![image](https://github.com/diazale/gt-dimred/assets/26947455/2f09a09a-226a-4e53-bb75-64c02e7dfaaf)

There is some similarity, but certainly not the same.  Can you please let me know how to replicate your plot?

Thanks!

Jie

**Comment by jielab** [comment]
When I used **-pc 10 -nn 15 -md 0.5 -nc 2** as recommended in your paper, I got the following plot. Now it looks quite close, but still not exactly the same.

![image](https://github.com/diazale/gt-dimred/assets/26947455/8975fcd2-f54b-41d1-ae2a-4f97edc83a73)

**Comment by sgravel** [comment]
These two plots are fairly similar to me. There are many UMAP configurations that are locally optimal, so it is possible that your umap implementation starts from different initial coordinates, and thus finds a different local minimum.   Some visual differences come from marker sizes (and colours, obviously!).

**Comment by jielab** [comment]
Thanks!

Can you please share your UMAP configuration for me to test-run it as well?

I would love to see that I could replicate your plot, to make sure that we got the same thing.

As you might agree, a map is all about precision :- )
Otherwise, drivers will get into trouble.

Best regards,
Jie

**Comment by diazale** [comment]
You won't be able to replicate it exactly as there is some randomness in the embedding (I forget if we used a random initialization, but also the optimization will be different). But looking at your figure, it's already quite close -- I recognize many of the shapes and clusters. You can colour/plot it following the notebook here: https://github.com/diazale/gt-dimred/blob/master/UKBB_cleaned.ipynb

The relevant sections for plotting are "Colours and labelling" and "Plotting (ethnicity)"

**Comment by jielab** [comment]
Thanks! I thought that PC and UMAP are two totally different methods. Now it is a bit surprising that UMAP are actually based on PC data. If I only have PC1 and PC2, and I used your script to get UMAP1 and UMAP2, will UMAP1 and UMAP2 be pretty much the same as PC1 and PC2?

Best regards,
Jie

**Comment by diazale** [comment]
PCA and UMAP are completely different methods and will return very different results. However, you can pre-process data with PCA first and then run PCs through UMAP as a denoising step or for computational tractability. We address this in our paper (https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008432). If you want to see the effects of using more PCs, see the supplementary figures.

**Comment by jielab** [comment]
Hi, sorry to come back on this again :- )

Below is the scatter-plot of **PC1 and PC2**, colored by **self-reported race/ethnicity**. This plot is consistent with what is shown in the UK Biobank 2018 Nature paper.
![image](https://github.com/diazale/gt-dimred/assets/26947455/b9f0656a-da8c-4b83-8cf9-8396fa62d27a)

Now, below is the scatter-plot of **UMAP1 and UMAP2**, generated by using your script. This is quite like your plot, as we previously discussed.
![image](https://github.com/diazale/gt-dimred/assets/26947455/f0135079-834f-48f9-b531-94ca18d08bf3)

Based on the Figure 1 of a **2023 Nature paper**, https://www.nature.com/articles/s41586-023-06079-4/figures/1, a **genetic distance** could be calcualted for each individual, based on PC1 and PC2. 

Do you think that I could calculate such a genetic distance based on UMAP1 and UMAP2 as well? I guess the answer is NO, since **UMAP1 and UMP2 are not orthogonal**, correct?

Your feedback would be greatly appreciated!

Thank you & Best regards,
Jie

**Comment by diazale** [comment]
Correct, distances cannot be calculated in UMAP space as it only preserves local neighbourhoods.

I will note that "race" is not a correct label for the data here (I'm assuming for the 1KGP you used the continental population). The field of population genetics is moving away from using race and ethnicity as descriptors for genetic data as they are not accurate and have led to confusion or misinterpretation (e.g. see some guidelines here: https://www.nature.com/articles/s41588-024-01708-8). I have written about this in the context of UMAP and clustering in the discussion section of my follow-up paper: https://www.biorxiv.org/content/10.1101/2023.07.06.548007v1

**Comment by jielab** [comment]
Thanks, Alex!

I agree that race might not be a correct label. That is why i am trying to use genetic distance, as shown in this Nature paper Figure 1 https://www.nature.com/articles/s41586-023-06079-4/figures/1, mentioned in my previous email.

Best regards,
Jie
